#! /bin/sh

prefix=/usr/local
dpkg_var=${prefix}/var/dpkg

PATH=${dpkg_var}/bootstrap:/bin:/sbin:/usr/bin:/usr/sbin

mkdir -p ${dpkg_var} ${dpkg_var}/alternatives ${dpkg_var}/info ${dpkg_var}/methods ${dpkg_var}/parts ${dpkg_var}/triggers ${dpkg_var}/updates
touch ${dpkg_var}/available
touch ${dpkg_var}/status

exec dpkg -i ${dpkg_var}/bootstrap/dpkg_1.14.30-3_darwin-universal.deb
