#! /bin/sh

prefix=/usr/local
dpkg_var=${prefix}/var/dpkg

PATH=${dpkg_var}/bootstrap:/bin:/sbin:/usr/bin:/usr/sbin

set -e
mkdir -p ${dpkg_var} ${dpkg_var}/alternatives ${dpkg_var}/info ${dpkg_var}/methods ${dpkg_var}/parts ${dpkg_var}/triggers ${dpkg_var}/updates
touch ${dpkg_var}/available
touch ${dpkg_var}/status

dpkg --refuse-downgrade -i ${dpkg_var}/bootstrap/dpkg_1.14.30-nx3_darwin-universal.deb
dpkg --refuse-downgrade -i ${dpkg_var}/bootstrap/apt_0.7.20.2-nx8_darwin-universal.deb
